FROM node:18-alpine

# Create app directory
WORKDIR /app

# Copy package.json
COPY package.json ./

# Install dependencies
RUN npm install

# Copy server.js file
COPY server.js .

# Copy ping file
COPY ping .

# Expose port
EXPOSE 8000

# Start the server
CMD ["node", "server.js"]
