version: '3.8'

services:
  nca-toolkit:
    image: stephengpope/no-code-architects-toolkit:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - API_KEY=thekey
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY=admin
      - S3_SECRET_KEY=password123
      - S3_BUCKET_NAME=nca-toolkit
      - S3_REGION=None
    depends_on:
      - minio
    restart: unless-stopped

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password123
    command: server /data --console-address ":9001"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  kokoro-tts:
    image: ghcr.io/remsky/kokoro-fastapi-cpu:v0.2.2
    ports:
      - "8880:8880"
    restart: unless-stopped

volumes:
  minio_data:
    driver: local
