[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckEnabled = true
healthcheckPath = "/ping"
healthcheckTimeout = 10
healthcheckInterval = 15
startCommand = "/app/entrypoint.sh"

[service]
internal_port = 8000
auto_deploy_on_push = true

[[ports]]
port = 8000
internal_port = 8000

[[ports]]
port = 5678
internal_port = 5678

[[ports]]
port = 8080
internal_port = 8080

[[ports]]
port = 8880
internal_port = 8880

[[ports]]
port = 9000
internal_port = 9000

[[ports]]
port = 9001
internal_port = 9001

[[ports]]
port = 3000
internal_port = 3000

[[ports]]
port = 11434
internal_port = 11434
