[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.railway"

[deploy]
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckEnabled = true
healthcheckPath = "/ping"
healthcheckTimeout = 30
healthcheckInterval = 30

[service]
internal_port = 8000
auto_deploy_on_push = true

[[ports]]
port = 8000
internal_port = 8000
